name: Valist Publish
on:
  release:
    types: [published]
jobs:
  valist-publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TIMESTAMP=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      - uses: robinraju/release-downloader@v1.3
        with:
          repository: "Jannikio/lab"
          latest: true
          tarBall: true
          zipBall: true
          fileName: "*"
      - uses: valist-io/valist-github-action@v2.2.0
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          account: nasdf
          project: Jannikio
          release: ${{ env.TIMESTAMP }}
          files: '**'
